version: "3.7"

services:
  mongo-dev:
    image: "mongo:latest"
    container_name: mongo_prod
    networks:
      - prod
    environment:
      - MONGO_INITDB_DATABASE=diet
    volumes:
      - db:/data/db
    expose:
      - 27017
    ports:
      - 27217:27017

volumes:
  db:

networks:
  prod:
    driver: bridge
